# Generated by Django 5.2.1 on 2025-06-04 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsortiumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consortium_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='taf_records.consortiummember')),
            ],
        ),
        migrations.CreateModel(
            name='TAFRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('country', models.CharField(choices=[('Philippines', 'Philippines'), ('Indonesia', 'Indonesia'), ('Vietnam', 'Vietnam'), ('Mozambique', 'Mozambique'), ('Other Countries', 'Other Countries')], max_length=100)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(choices=[('regional', 'Regional'), ('national', 'National'), ('City/Municipal', 'City/Municipal'), ('site-level', 'Site-level')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_ta', models.CharField(choices=[('Capacity-building', 'Capacity-building'), ('Research', 'Research'), ('Policy Support', 'Policy Support'), ('Technical Advice', 'Technical Advice'), ('Others', 'Others')], max_length=100)),
                ('type_of_ta_other_details', models.TextField(blank=True, null=True)),
                ('themes_text', models.TextField(blank=True, help_text='Comma-separated list of themes', null=True)),
                ('theme_other_details', models.TextField(blank=True, null=True)),
                ('experts_involved_flag', models.BooleanField(default=False, verbose_name='Experts/Institutions Involved?')),
                ('experts_details_text', models.TextField(blank=True, null=True, verbose_name='Details of Experts/Institutions')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_experts', models.ManyToManyField(blank=True, related_name='taf_records', to='taf_records.expert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_taf_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
