# Generated by Django 5.2.1 on 2025-06-04 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taf_records', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Concept Note', 'Concept Note'), ('Terms of Reference', 'Terms of Reference'), ('Full Proposal', 'Full Proposal'), ('Budget TA Contract', 'Budget TA Contract'), ('Deliverables/Milestone Outputs', 'Deliverables/Milestone Outputs'), ('Invoices', 'Invoices'), ('Proof of Payment', 'Proof of Payment'), ('Evaluation Report', 'Evaluation Report'), ('References', 'References'), ('Other Files', 'Other Files')], max_length=100, null=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('taf_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='taf_records.tafrecord')),
                ('template_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='templates.template')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
